name: pr

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  Build:
    name: Build
    permissions:
      statuses: write
      pull-requests: write
    uses: ./.github/workflows/_build.yml
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}

  BuildDocs:
    name: Build Docs
    permissions:
      statuses: write
      pull-requests: write
    uses: ./.github/workflows/_build-docs.yml

  Dependabot:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2.4.0
        with:
          github-token: "${{ steps.app-token.outputs.token }}"
      
      - name: Add bpk label
        if: contains(steps.dependabot-metadata.outputs.dependency-names, 'bpk-')
        run: gh pr edit "$PR_URL" --add-label "bpk" --remove-label "javascript"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{github.event.pull_request.html_url}}

      - name: Apply appropriate dependency labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const updateType = '${{ steps.dependabot-metadata.outputs.update-type }}';
            const prNumber = context.issue.number;
            
            // Map update types to appropriate labels
            let labelToAdd = 'dependencies'; // fallback
            
            switch(updateType) {
              case 'version-update:semver-major':
              case 'version-update:semver-premajor':
                labelToAdd = 'majorDependency';
                break;
              case 'version-update:semver-minor':
              case 'version-update:semver-preminor':
                labelToAdd = 'minorDependency';
                break;
              case 'version-update:semver-patch':
              case 'version-update:semver-prepatch':
                labelToAdd = 'patchDependency';
                break;
              default:
                labelToAdd = 'dependencies';
                break;
            }
            
            // Get current labels
            const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });
            
            const currentLabelNames = currentLabels.map(label => label.name);
            const conflictingLabels = ['major', 'minor', 'patch'];
            
            // Remove conflicting labels if they exist
            for (const conflictingLabel of conflictingLabels) {
              if (currentLabelNames.includes(conflictingLabel)) {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  name: conflictingLabel
                });
                console.log(`Removed conflicting label: ${conflictingLabel}`);
              }
            }
            
            // Remove the generic 'dependencies' label if we're adding a specific one
            if (labelToAdd !== 'dependencies' && currentLabelNames.includes('dependencies')) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                name: 'dependencies'
              });
              console.log('Removed generic dependencies label');
            }
            
            // Add the appropriate label if it's not already present
            if (!currentLabelNames.includes(labelToAdd)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: [labelToAdd]
              });
              console.log(`Added label: ${labelToAdd} for update type: ${updateType}`);
            } else {
              console.log(`Label ${labelToAdd} already present`);
            }
